spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
    username: root
    password: rootroot
  thymeleaf:
      cache: false
      prefix: classpath:/templates/
      suffix: .html
      encoding: utf-8
      mode: html5
      servlet:
        content-type: text/html



mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: hugh.tech.learn.entity


#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql